const colors = {
    col1: 'white',
    text1: 'blue',
    text2: 'grey', 
    text3: '#344055',
    text3: '#7d7d7d',
    text4: '#4F4F4F',
    black: 'black',
    footer: '#ccc',
    primary: '#344055',
    secondary: '#4c5dab',
    para: '#7d7d7d',
    line: '#4c5dab',
    success: '#4CAF50',
    warning: '#FFEB3B',
    error: '#F44336',
    text: '#212121',
    background: '#F5F5F5',
    bg: '#ffffc6',
    cardBgColor: "#dadccb",
    btnBgColor: '#809fff',
    yellow: '#FFFF00',
    drvoilet: '#aa18ea',
    drcg: '#333',
    toggle_backgroundColorOn: "#4cd137",
    toggle_backgroundColorOff: "#ecf0f1",
    toggle_circleColorOff: "#bdc3c7",
    toggle_circleColorOn: "#f5f6fa",
    
};

export default colors;